### ISSUE TITLE
Add api/login endpoint

### ISSUE THREAD

**Issue by GoodbyePlanet** [z0bla/kid-toys-service#29]
AC:

- endpoint `api/login` is created (should be POST request)
- should check if user exists - if not the server should respond with 401 Unauthorized response code
- should check if password is correct - if not the server should respond with 401 Unauthorized response code
- user password should be decripted with bcryptjs
- if user email exists and password is correct server should respond with 200 response code and should  return object with signed `jwtToken` - token should consist of `user.id` and `user.role`
- read about jwt tokens here https://jwt.io/

**Comment by goranstevanovic** [comment]
See #49.
